import type { AuditReport, Category, Finding, Severity } from '../types.js';

const SEV_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

const SEV_LABEL: Record<Severity, string> = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
  info: 'Info',
};

const CAT_LABEL: Record<Category, string> = {
  SECRETS: 'Secrets',
  DEPS: 'Dependencies',
  SAST: 'SAST',
  DEAD_CODE: 'Dead Code',
  IaC: 'IaC',
  PATTERNS: 'Patterns',
  DUPLICATION: 'Duplication',
  COMPLEXITY: 'Complexity',
  DEP_HEALTH: 'Dep Health',
  LICENSE: 'License',
  AI_CODE: 'AI Code',
  GIT_HEALTH: 'Git Health',
  TYPE_SAFETY: 'Type Safety',
};

export function formatMarkdown(report: AuditReport, aiSummary?: string): string {
  const lines: string[] = [];

  // ─── Header ──────────────────────────────────────────────────────────────
  lines.push(`# 🛡️ auditx Security Report`);
  lines.push('');
  lines.push(`**Target**: \`${report.meta.target}\``);
  lines.push(`**Scanned**: ${new Date(report.meta.scannedAt).toLocaleString()}`);
  lines.push(`**Duration**: ${(report.meta.durationMs / 1000).toFixed(1)}s`);
  lines.push(`**Stack detected**: ${report.meta.stack.join(' · ') || 'Unknown'}`);
  lines.push(`**Scanners run**: ${report.meta.scanners.join(' · ')}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ─── Summary table — FIXED: iterate every category, not hardcoded subset ──
  lines.push('## Summary');
  lines.push('');
  lines.push('| Category | 🔴 Critical | 🟠 High | 🟡 Medium | 🔵 Low | ⚪ Info |');
  lines.push('|---|---|---|---|---|---|');

  const allCategories = Object.keys(CAT_LABEL) as Category[];
  for (const cat of allCategories) {
    const catFindings = report.findings.filter((f) => f.category === cat);
    if (catFindings.length === 0) continue;
    const counts = countBySeverity(catFindings);
    lines.push(
      `| ${CAT_LABEL[cat]} | ${counts.critical || '—'} | ${counts.high || '—'} | ${counts.medium || '—'} | ${counts.low || '—'} | ${counts.info || '—'} |`,
    );
  }

  const total = report.summary;
  const totalInfo = report.findings.filter((f) => f.severity === 'info').length;
  lines.push(
    `| **Total** | **${total.critical}** | **${total.high}** | **${total.medium}** | **${total.low}** | **${totalInfo}** |`,
  );
  lines.push('');

  const urgentCount = total.critical + total.high;
  if (urgentCount > 0) {
    lines.push(`> ⚠️ ${urgentCount} high/critical finding${urgentCount > 1 ? 's' : ''} require immediate attention.`);
  } else {
    lines.push('> ✅ No critical or high severity findings.');
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // ─── Findings by severity ──────────────────────────────────────────────
  const severityGroups: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

  for (const sev of severityGroups) {
    const sevFindings = report.findings.filter((f) => f.severity === sev);
    if (sevFindings.length === 0) continue;

    lines.push(`## ${SEV_EMOJI[sev]} ${SEV_LABEL[sev]} (${sevFindings.length})`);
    lines.push('');

    // low/info collapsed by default — keeps report scannable at scale, still fully present for agents
    const collapse = (sev === 'low' || sev === 'info') && sevFindings.length > 5;
    if (collapse) {
      lines.push('<details>');
      lines.push(`<summary>Show ${sevFindings.length} ${SEV_LABEL[sev].toLowerCase()} findings</summary>`);
      lines.push('');
    }

    for (const finding of sevFindings) {
      lines.push(renderFinding(finding));
    }

    if (collapse) {
      lines.push('</details>');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // ─── AI Analysis (LLM-generated summary, if --ai used) ─────────────────
  if (aiSummary) {
    lines.push('## 🤖 AI Analysis');
    lines.push('');
    lines.push(aiSummary);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // ─── Machine-readable block for agent loops ─────────────────────────────
  // Agents scraping the .md file (not the --output json mode) get a parseable
  // anchor instead of having to regex the prose above.
  lines.push('## Machine-Readable Summary');
  lines.push('');
  lines.push('```json');
  lines.push(
    JSON.stringify(
      {
        exitCode: urgentCount > 0 ? 1 : 0,
        urgentCount,
        totalFindings: report.findings.length,
        fixableCount: report.findings.filter((f) => Boolean(f.fix)).length,
        filesAffected: new Set(report.findings.map((f) => f.file).filter(Boolean)).size,
        topFiles: topOffendingFiles(report.findings, 5),
      },
      null,
      2,
    ),
  );
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ─── Footer ──────────────────────────────────────────────────────────────
  lines.push(`*Generated by [auditx](https://github.com/parth308/auditx) · MIT License*`);

  return lines.join('\n');
}

function renderFinding(f: Finding): string {
  const lines: string[] = [];

  const anchor = f.id ? `<a id="${f.id}"></a>` : '';
  lines.push(`### ${anchor}[${f.category}] ${f.title}`);

  if (f.file) {
    const location = f.line ? `${f.file}:${f.line}` : f.file;
    lines.push(`- **File**: \`${location}\``);
  }
  if (f.cve) lines.push(`- **CVE**: \`${f.cve}\``);
  if (f.cvss !== undefined) lines.push(`- **CVSS**: ${f.cvss}`);
  if (f.packageName && f.packageVersion) {
    lines.push(`- **Package**: \`${f.packageName}@${f.packageVersion}\``);
  }
  if (f.rule) lines.push(`- **Rule**: \`${f.rule}\``);
  if (f.description) lines.push(`- **Description**: ${f.description}`);
  if (f.match) lines.push(`- **Match**: \`${f.match}\``);
  if (f.inGitHistory) {
    lines.push(`- **In git history**: ⚠️ Yes — rotating the credential is mandatory`);
  }
  if (f.fix) lines.push(`- **Fix**: ${f.fix}`);

  lines.push('');
  return lines.join('\n');
}

function countBySeverity(findings: Finding[]) {
  return {
    critical: findings.filter((f) => f.severity === 'critical').length,
    high: findings.filter((f) => f.severity === 'high').length,
    medium: findings.filter((f) => f.severity === 'medium').length,
    low: findings.filter((f) => f.severity === 'low').length,
    info: findings.filter((f) => f.severity === 'info').length,
  };
}

function topOffendingFiles(findings: Finding[], n: number): { file: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const f of findings) {
    if (!f.file) continue;
    counts.set(f.file, (counts.get(f.file) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([file, count]) => ({ file, count }));
}